title: "notations"
repository: Habbianos/notations
description: >-
  Notations and some important data structures used in Habbo Hotel
theme: jekyll-theme-minimal
plugins:
  - jekyll-gfm-admonitions

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "*.ts" # Also those in the root directory!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
